### ISSUE TITLE
Disconnects and then doesn't recognize

### ISSUE THREAD

**Issue by AGPVEN** [bandapps/bandapps.github.io#1]
Hi, I purchased Band Time Tracker. It worked great for a few hours. But then it not only disconnect from my Band 2, it also did not recognize that I already had the corresponding tile. I had to remove the tile and then start over again. The good news is that my previous recorded intervals were not deleted. 

Thanks for taking a look into this.

**Comment by J-L** [comment]
Hey AGPVEN,
First up, I have seen the band not able to send events to the iOS App, and I believe this is primarily caused by your iPhone force quitting the app.  iOS does memory management, and on occasion the operating system will kill the app altogether as it thinks the app is not doing anything important. As an app designer, there isn't a bullet proof way of dealing with this, though I might be able to something to make it less problematic.  

Which version iPhone/OS are you running?

Secondly, can I ask you what you mean by didn't recognize  the tile already on there?  Did it try to add a new tile, or did it just not respond to the Band's button presses?

Thanks,

John

**Comment by AGPVEN** [comment]
Hi John:

I'm running 9.2.1

What happens is that I'll have a timer running which I have initiated from
the band. Some time passes. Then I'll go on band to stop the the timer and
it a unresponsive.

I go to the app and it gives me the message that I don't have to make space
for another tile. I try several times and I keep getting the message.

I remove the timer tile and that clears out the problem.

However, after resetting it back to the original state and then adding the
tile back on, the same freeze out occurs again.

Thanks. Great idea for a app. I hope you're able to getting it working.

Thx

On Friday, January 22, 2016
, John Justin Lee <notifications@github.com> wrote:

> Hey AGPVEN,
> First up, I have seen the band not able to send events to the iOS App, and
> I believe this is primarily caused by your iPhone force quitting the app.
> iOS does memory management, and on occasion the operating system will kill
> the app altogether as it thinks the app is not doing anything important. As
> an app designer, there isn't a bullet proof way of dealing with this,
> though I might be able to something to make it less problematic.
>
> Which version iPhone/OS are you running?
>
> Secondly, can I ask you what you mean by didn't recognize the tile already
> on there? Did it try to add a new tile, or did it just not respond to the
> Band's button presses?
>
> Thanks,
>
> John
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bandapps/bandapps.github.io/issues/1#issuecomment-174125366>
> .
>


-- 
Sent from my iPhone...via Miniuum and Fleksy

**Comment by J-L** [comment]
Hey!
I think I have enough information to get a fix in now, I've reproduced it on my band. I'll fix it and push it to the app store asap- which will take approximately a week to get to you.

In the mean time  the only solution is to remove another tile so the app passes that check. sorry about that :(.

**Comment by AGPVEN** [comment]
hey...no prob whatsoever. Expect a very positive review from me.  I am also
glad that developers like you are finally getting more and more useful
non-workout related apps for the Band. I'm a long time user of time
tracking apps and I like how allows me to track time, without taking my
phone out of my pocket.

Thanks again for your hard work. Looking forward to the update.

**Comment by J-L** [comment]
Hey I've posted the update to the app store.  You should see it in apple review time (approx 7 days as I write)

Thanks again for posting this issue.
John

**Comment by AGPVEN** [comment]
thx, I see the update!
