### ISSUE TITLE
Feature request: send identifier 

### ISSUE THREAD

**Issue by chriskacerguis** [bandapps/bandapps.github.io#10]
Me again!  I wanted to get 2 bands to post to the same post URL and I was wondering if you could add a field for an identifier that you could set as part of the post setting so I could tell the two apart.

**Comment by bandapps** [comment]
Hey, yeah- I think I can do that. Problem is i wouldn't know what to add as the unique id. I haven't seen an identifier in the sdk. I could generate a uuid and maintain it, but if the app is uninstalled it would lose it.

Any thoughts?

**Comment by chriskacerguis** [comment]
I would just add a text field and let people put in whatever they want (like how it is with the post URL)

**Comment by J-L** [comment]
Would you like to beta test 1.3 with the changes you have suggested?

**Comment by chriskacerguis** [comment]
That's be great.  Thanks!

**Comment by chriskacerguis** [comment]
Hello. Just wondering if you needed someone to help beta test?

**Comment by bandapps** [comment]
Hey chris, whats your email address: email it to me directly at johnjusttinlee@me.com

**Comment by chriskacerguis** [comment]
Hi John. Your email bounced.

**Comment by J-L** [comment]
johnjustinlee@me.com <mailto:johnjustinlee@me.com>

oops.

**Comment by J-L** [comment]
in 1.3!
