### ISSUE TITLE
Band health bridge crashing

### ISSUE THREAD

**Issue by mrose17** [bandapps/bandapps.github.io#11]
Right after it displays "updated tokens successfully"

How can I debug?

**Comment by bandapps** [comment]
Unfortunately, I didn't catch a exception and it crashes if the token failed- essentially Microsoft is reprompting for authorization again... 

I have a build in review queue, do you mind if I add you to a beta build in the mean time?

**Comment by mrose17** [comment]
that'd be great. i'm sending you my UDID...

**Comment by J-L** [comment]
Should be fixed in 1.1. apologies!
