### ISSUE TITLE
How to get URL to post band data?

### ISSUE THREAD

**Issue by JohnnyF7** [bandapps/bandapps.github.io#13]
Hello,

I am having a lot of trouble trying to post data from my microsoft band 2 using the band lab app to a server. Can the server be a URL from google spreadsheet? This is what i have been trying and its not working.

Please help!
Thank you,
Johnny

**Comment by J-L** [comment]
Hey Johnny,

The server you are point it to needs to know about whats getting posted to it.  Google spreadsheets will not know what is happening.  You will need to write a server application which accepts the input and does something with it.  Can I ask what you are trying to do with the data, that way I can give you a better answer?


Best regards

John Lee

**Comment by JohnnyF7** [comment]
Hello John,

Thank you for replying to my post!

I see.. So what I was doing wouldn't allow me to see the raw json data just
put into the spreadsheet url..

All I am trying to do is aquire the data, namely from the accelerometer,
convert it to excel sheets, text file, etc. anything that I can use to
directly put the data into Matlab so I am able to play around with it
through some preprocessing of different arm motions.

I have been searching many sites, but I guess what I am not understanding
is how to get a working server, just so I can take the data?

Does that make sense?

Thank you again,
Johnny

**Comment by J-L** [comment]
Is this for school? Uni? 

The topic of server side programming is a little too broad for me to go into detail here.  What programming languages are you familiar with?  I have been intending to create a server side component to catch all the data, but right now its a pretty low priority for me. 

John

**Comment by JohnnyF7** [comment]
This is for uni, applying machine learning techniques to distinguish
between different arm movements while wearing the band.

I'm only really familiar with Matlab. I know a bit of Python but not too
much.

So I would need code to catch the data? How does the code translate to
inputting a url in the app?

Thanks for your help again,
Johnny

**Comment by J-L** [comment]
The URL would be the (most likely) ip address where the server is listening. This is most likely the address of your laptop or desktop.  The code you write would listen and interpret the json that band lab transmits

Here is a link to the format that will be outputted:
http://bandapps.github.io/band-lab-released.html

As you know python, I personally recommend Flask as the web framework:
http://flask.pocoo.org

Keep in mind the Band generates data at 31 samples/ second. Nyqvist implies the best signal you can get is therefore less than 15hz, most likely much less than this.

Best regards

John

**Comment by JohnnyF7** [comment]
Thanks John!

I'll give that a look and try and get everything set up. I never knew I
could use the IP address of my laptop. I guess I'll just need to know how
to write the code in order to obtain the json then convert it later.

Thank, I really appreciate your help.
Johnny

**Comment by J-L** [comment]
In the meantime you can type this into a terminal on your computer:
python -m SimpleHTTPServer 8000

find your ip address and put it into band lab as ipaddress:8000 and watch the app call your laptop

**Comment by JohnnyF7** [comment]
Hi John,

I tried putting that in, but nothing seems to be happening.

What is the best way to obtain the JSON files that contains the data from
the app. Is there a simple way I can just put a url or anything into the
app, press post data, and obtain the JSON files?

I'm sorry if I sound ignorant on the subject.. I'm still learning about
servers, file sources, etc. I'm really confused on what to put in the post
data tab of the app.

I came across this initially,
https://coderwall.com/p/duapqq/use-a-google-spreadsheet-as-your-json-backend

And using that url into the post data tab in the app. Is this what the post
data tab is for? The 'backend' for reading the JSON data? Because I feel
like once I have the JSON data, it's really not hard to convert that into a
format that I will work with for data analysis.

Thanks again John,
Johnny.

**Comment by J-L** [comment]
Hey, 
Im a little swamped with other work right now, but.. to get started on Flask, I learned through using this guys book: http://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-i-hello-world . Its relatively straight forward and he's got enough details on his website that you can get started without paying (though I recommend it) .  

The crux of the design is this:

You create an endpoint to take in the data and point the app to that server. Then you have flask create an  object from the json and with help from SQLAlchemy (which will expedite your database design).  You then create other endpoints to draw the data back from the database. Output back to JSON so your javascript application can easily read it.  The javascript app, use whatever framework you want, theres a million now.

It might take a little while to get started, but one you get rolling you'll find it easy.

Best regards

John

**Comment by johnabela** [comment]
@J-L do you see a point in time when you are going to be able to apply a rate limiter on your end (the app)?

Reading data streams at "31 samples/ second" is just brutal, and in many cases impossible, for us to try handling on our end (the server).

**Comment by johnnyvenom** [comment]
Hey, thanks for the reply. I went through that same tutorial last week. SQLAlchemy works great. Once I get something up and running I'll share the results here. I was also wondering about the last comment, how a server can handle that rate of data.  

...Also, nice - this thread is entirely made up of people named John ;)

**Comment by J-L** [comment]
Hey all, 
Ive created an update but, I haven't had a chance to look at it(particularly the server side).  If you'd like to beta test it please email me your email address.  this update allows unique naming of each band, and has a request divisor. it will concatenate requests then launch them in a single request.

Thanks
John

**Comment by prernaa** [comment]
Hi John,
Do you have some sample code for the server-side JSON hander?
Cheers,
Prerna

**Comment by johnnyvenom** [comment]
Hi J-L - 

I've set up a couple simple server applications to receive the streaming band data, but packages are coming sporadically and infrequently. Any idea why? 

Also, please sign me up to beta test the update with the request divisor. 

@prernaa - I think we are all here trying to get a working server-side JSON handler. I am looking to stream data to Max, and there are some built-in TCP objects and JSON parsing. But for now the realtime streaming is problematic.. 

Cheers,
Johnny

**Comment by johnnyvenom** [comment]
Another question, is the iOS app waiting for a confirmation message from the server after sending each package, and if so, is this why the messages are not streaming regularly? I.e., they would be held because there was no confirmation from the previous message, but eventually the app will time out and send the next message anyways?

**Comment by bandapps** [comment]
Hey All, I spun something up quickly.

Try it out here:
https://github.com/bandapps/BandSensorCollector

**Comment by bandapps** [comment]
you can offer pull requests if you want to add. Right now it will just print out everything it receives

**Comment by bandapps** [comment]
Band Sensor collector Available.

**Comment by DushyantDhundara** [comment]
Hi John,
I am trying to replicate this in MATLAB. I am wondering if I would need to call python libraries in it, or how do I implement your code to retrieve real time data to be used in MATLAB? Thank you

**Comment by J-L** [comment]
You can use the flask/python server code I have provided and modify it to write to file, or generate cvs which can be read in to matlab. I don't believe matlab can be used as a server app directly

**Comment by DushyantDhundara** [comment]
Could you please direct where that code is in the folder you have up here? I haven't dealt with python or server side of programming before. Matlab does allow to call python

**Comment by J-L** [comment]
https://github.com/bandapps/BandSensorCollector <https://github.com/bandapps/BandSensorCollector>

**Comment by DushyantDhundara** [comment]
I think I didn't work my question properly, Yes I see that code, but which is the main file that I run which calls all the functions. I am sure not sure about the specific purpose of each file you have!

**Comment by bandapps** [comment]
To be honest, the instructions are actually on that page… :|

pip install -r requirements.txt
To run:

python ./runserver.py
Now point Band Sensor to :

local_ipaddress:5000/collector and restart app

**Comment by DushyantDhundara** [comment]
I guess I would need to understand how to implement this in MATLAB first. Just to be sure, this code pulls data directly off the app or does it get data from the MS Health Band Dashboard. I am trying to follow the instructions here: [API](https://developer.microsoftband.com/cloudAPI)

**Comment by bandapps** [comment]
So band experimental gets the data directly from the band… the server code would get it directly from band experimental.

The cloud API is only used in Band health bridge and Health Ark.

**Comment by bandapps** [comment]
Impementing a server in Matlab…. i don’t think matlab does that.

**Comment by DushyantDhundara** [comment]
So what would you suggest to do if I want to perform a analysis on the real time data ?

**Comment by bandapps** [comment]
Learn a bit of python, at least to the point where you can convert the print statement in collector.py to a format you’d like to output… you could either then pipe that data into matlab or analyze it in python directly.  What are you looking to build?

John

**Comment by DushyantDhundara** [comment]
Ok sounds good, I am just trying to stream in real time data and then provide live graphs to the user

**Comment by bandapps** [comment]
I'd change the print statement to write to a csv... Then I would make matlab continuously read the last X values of it

**Comment by DushyantDhundara** [comment]
makes sense, I think I first need to learn to implement this in Python and then go from there

**Comment by DushyantDhundara** [comment]
Are these run from windows cmd: 

pip install -r requirements.txt
To run:
python ./runserver.py
Now point Band Sensor to :
local_ipaddress:5000/collector and restart app

When I opened the code runserver.py in IDLE, and ran it, I got an error "from tornado.wsgi import WSGIContainer ImportError: No module named 'tornado'"
Do all these codes have to to be in the same folder? Sorry my questions are very naive, I do not have background in this kind of programming
