### ISSUE TITLE
Issue syncing height - scale off

### ISSUE THREAD

**Issue by jfurtner** [bandapps/bandapps.github.io#14]
My Band / MS Health site is set to Metric, and my height was entered in centimeters (183), but when synchronizing it comes across as though it's in milimeters (1830).

Can the scale be corrected so it's reported in centimeters?

**Comment by jfurtner** [comment]
You can see a screen shot from Apple Health here: [https://goo.gl/photos/bENeuyia5F1d67kr8](url)

**Comment by jfurtner** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1195789/13021378/1fe91aae-d198-11e5-87c3-b88bf36d0487.png)

Screen shot from Apple Health.

**Comment by J-L** [comment]
Hey J,
Thanks for reporting this issue.  I've fixed the conversion in my code. It will be in the next revision of the app, which I plan to release whenever I figure out how to background sync correctly.

Best regards, and thanks for reporting this!

John

**Comment by J-L** [comment]
Should be in 1.2!
