### ISSUE TITLE
Heart rate 

### ISSUE THREAD

**Issue by AGPVEN** [bandapps/bandapps.github.io#15]
Hi, thanks for getting it working on steps, running and stairs. But no data seems to collected for heart rate, ethic one of the more interesting metrics collected in the band. I've got Band enabled for that in the health app. Is that something you can fix?

**Comment by J-L** [comment]
Hey AGPVEN, 

Heart rate is definitely !!! in there. Can you check your health app, go to heart rate and go to data?

I have not heard that the app isn't pushing heart rate.  Is Active Energy/ Steps/Distance being updated?

**Comment by J-L** [comment]
Where are you located AGPVEN?

**Comment by AGPVEN** [comment]
I'm in southern California, how about you?

Regarding the settings, it seems that everything you mentioned is enabled.
The one thing that I thought might be a problem is that I have two other
heart tracking devices. But weeks ago I disabled tracking on them.

On Saturday, February 13, 2016, John Justin Lee <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> Where are you located AGPVEN?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bandapps/bandapps.github.io/issues/15#issuecomment-183796100>
> .
>


-- 
Sent from my iPhone...via Miniuum and Fleksy

**Comment by AGPVEN** [comment]
I sent four images. Hopefully the all got to you.

On Saturday, February 13, 2016, birdvibe@gmail.com <birdvibe@gmail.com>
wrote:

> I'm in southern California, how about you?
>
> Regarding the settings, it seems that everything you mentioned is enabled.
> The one thing that I thought might be a problem is that I have two other
> heart tracking devices. But weeks ago I disabled tracking on them.
>
> On Saturday, February 13, 2016, John Justin Lee <notifications@github.com>
> wrote:
>
>> Where are you located AGPVEN?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bandapps/bandapps.github.io/issues/15#issuecomment-183796100>
>> .
>>
>
>
> --
> Sent from my iPhone...via Miniuum and Fleksy
>


-- 
Sent from my iPhone...via Miniuum and Fleksy

**Comment by J-L** [comment]
Hey AGVEN,

I know what the problem is.  If you go to your Apple Health> Heart Rate> Share Data You will see all the of apps you have that are allowed to use and insert data. Band Health Bridge should be the top of the list, or the others will override it.

Best regards,

John

**Comment by AGPVEN** [comment]
Ok will try

On Saturday, February 13, 2016, John Justin Lee <notifications@github.com>
wrote:

> Hey AGVEN,
>
> I know what the problem is. If you go to your Apple Health> Heart Rate>
> Share Data You will see all the of apps you have that are allowed to use
> and insert data. Band Health Bridge should be the top of the list, or the
> others will override it.
>
> Best regards,
>
> John
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bandapps/bandapps.github.io/issues/15#issuecomment-183811031>
> .
>


-- 
Sent from my iPhone...via Miniuum and Fleksy

**Comment by AGPVEN** [comment]
I put Heath Bridge at the top. I haven't seen any immediate charge.

I tapped Heath Bridge and there is no data. See the screen capture.

On Saturday, February 13, 2016, birdvibe@gmail.com <birdvibe@gmail.com>
wrote:

> Ok will try
>
> On Saturday, February 13, 2016, John Justin Lee <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Hey AGVEN,
>>
>> I know what the problem is. If you go to your Apple Health> Heart Rate>
>> Share Data You will see all the of apps you have that are allowed to use
>> and insert data. Band Health Bridge should be the top of the list, or the
>> others will override it.
>>
>> Best regards,
>>
>> John
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/bandapps/bandapps.github.io/issues/15#issuecomment-183811031>
>> .
>>
>
>
> --
> Sent from my iPhone...via Miniuum and Fleksy
>


-- 
Sent from my iPhone...via Miniuum and Fleksy

**Comment by bandapps** [comment]
Hey, I actually never got any photos :(

**Comment by AGPVEN** [comment]
​is there a way to send you images.

I can send them to your personal email. They may shed some light on the
problem. That's unless I need to wait a while for data accumulate.

My personal email address is birdvibe@gmail.com​

**Comment by bandapps** [comment]
My personal email is johnjustinlee@me.com

John
