### ISSUE TITLE
Data Gaps(Steps)

### ISSUE THREAD

**Issue by J-L** [bandapps/bandapps.github.io#16]

**Comment by tidders1980** [comment]
I seem to be getting sporadic data uploads I did 7000 steps but apple Healy is only showing 4000 any ideas

**Comment by bandapps** [comment]
Hey, 
Can you check data source under steps?  It could be the case that:
Another source is placed ahead of Band Health Bridge(ABOVE Band Health Bridge)
You walked without your band- Microsoft Health will import the steps your Phone records, but it wont go into your hourly activity.

Let me know the results, and Ill look into it.

**Comment by tidders1980** [comment]
I frequently walk with my band with my phone in my bag would that affect to data? I did walk today with just the band? I'm confused

**Comment by tidders1980** [comment]
Ps on the import it shows 0 on some lines.
