### ISSUE TITLE
Data loss

### ISSUE THREAD

**Issue by klevey** [bandapps/bandapps.github.io#17]
I I installed the latest update and apple health showed no data. I figured I'd delete all bridge app and reload all data.  When I try to do that it no longer allows me to sync back in time

**Comment by bandapps** [comment]
Hey, the date picker won't allow you to set a date in the future,even for a second. If you set year first then month it will work. Sorry about that, I should perhaps change it so it doesn't move it back until you hit go.

**Comment by klevey** [comment]
Thanks for the quick response.  It wouldn't let me go back past December 1, 2015. But that's not a big deal. 
Also something is wrong with Apple HealthKit as it no longer shows any data in it.  Strange
Thx

**Comment by bandapps** [comment]
I'll have to test that out. Have you looked under data sources for a band health bridge? If you have multiple data sources they need to be ordered in priority

**Comment by klevey** [comment]
I'll look at later but not sure where that is

**Comment by J-L** [comment]
Hey Klevey, 
I was driving so my responses were a bit short.

If you click on a individual data set-say heart rate, then go to to share data it will show you the list of data sources.  If they are ordered with something above Band Heath Bridge on top you will see the top source. 

You can also see what band health bridge has imported by going to Show All Data


Best regards

John

**Comment by klevey** [comment]
John
Great service by the way. I'm still having the problem.  I've included some screenshots.  Again I'm not sure if it is your issue

**Comment by klevey** [comment]
I rebooted my iPhone and the health app now works.  Sorry I bothered you.
Thank you for your prompt replies

**Comment by J-L** [comment]
No problem!

**Comment by klevey** [comment]
Johnone quick thing. I notice that the first time I sync bridge when I go into health all data is zero.  I then turn off the phone and open back up all is fine.  this has happened every day and its only the first time I sync in a day
CheersKen

**Comment by J-L** [comment]
Hey Ken,
I think what you are experiencing is apple health loading in the data.   It takes time for the data to be accepted by apple health.  if you kept it open long enough you would have seen the graphs be drawn over and over until it was filled in.  When band health bridge injects the data I don't think the Apple Health app processes it until the app starts... its pretty odd, but its not something I can change- although perhaps i should make my users aware of it.

Thanks

John

**Comment by klevey** [comment]
thanks Johnhave a great weekend
