### ISSUE TITLE
Unable to sync all the data

### ISSUE THREAD

**Issue by infiniteloop153** [bandapps/bandapps.github.io#18]
I can only sync the data to iOS health starting from the day I downloaded the app. Even though I selected a start date which is several months in past (Oct 2014), the app did not sync any of the old data. Anyone facing this problem?

**Comment by bandapps** [comment]
Hey Infinity, 

Try deleting and redownloading the app.  The date picker will reject any dates ahead of today, so set year first then month etc.  Then hit sync.  One thing that might be an issue is sometimes Apple health takes a while to load in all the data.(The processing is actually done by apple app, but needs Health Bridge to be open)  Leave the app open for a couple minutes after, my personal experience is that if i close it immediately it will miss a week, but obviously you’ve had your band much longer.

Let me know if this fixes it.  I used to have a delay of 0.3 seconds between requests, perhaps its necessary to avoid this issue.

Best regards

John

**Comment by infiniteloop153** [comment]
setting the year first, month second and then date did the trick. Awesome!
Thanks!

**Comment by bandapps** [comment]
No problem! I should fix that from a usability perspective... It's confusing.  Thanks
