### ISSUE TITLE
Feature request: Resting heart rate graph

### ISSUE THREAD

**Issue by 16Univ** [bandapps/bandapps.github.io#19]
Conspicuously absent from the Microsoft website or app are more metrics pertaining to heart rate. One commonly used metric is resting heart rate (avg of heart rate while awake and resting, such as while I'm typing now). Other fitness trackers, such as Fitbit or Garmin, provide a graph of the resting heart rate. I don't know why Microsoft is so behind the curve.

**Comment by bandapps** [comment]
Hey, thats a great idea! I'm building an OS X app for the Microsoft Band, do you mind if i roll this feature into it?

Best regards

John

**Comment by 16Univ** [comment]
Hi John

Does this mean you developed it?

Albert

**Comment by J-L** [comment]
Yep! OS X App now released- a full desktop client for microsoft health!

https://itunes.apple.com/us/app/health-ark-for-microsoft-band/id1094959498?ls=1&mt=12

![screen shot 2016-04-18 at 11 18 41 pm](https://cloud.githubusercontent.com/assets/2156480/14629511/130ddbdc-05bc-11e6-9b50-5e00830352a7.png)

Resting heart rate histogram to give you an idea of where you hr is :)

**Comment by 16Univ** [comment]
That looks brilliant, John!  But does that only run on OS X? I have an iPhone and a PC running Windows 10. Will you be developing the app for iOS?

**Comment by bandapps** [comment]
I’ve already ben asked for a port to iOS…. pc would be a stretch as it is a native app written in swift!

We’ll see :)

Best regards

John
