### ISSUE TITLE
Sensor data request: Galvanic Skin Response (Electrodermal Activity)

### ISSUE THREAD

**Issue by eximiusvir** [bandapps/bandapps.github.io#21]
Hey John,
I've been reviewing (and attempting to map) the various HealthKit measurements to the sensors available in the MS Band 2. 

Really appreciating the fact I can get my MS Band data in Apple Health. (thanks for this app!) Just listing these for tracking purposes.

**Comment by J-L** [comment]
Hey Eximius,

Currently the Microsoft Health API exposes no way to get GSR from the cloud, which is what I use to populate Apple Health. Same with UV Index!
