### ISSUE TITLE
User Education: Sync'ing weight via Health Band Bridge (HBB)

### ISSUE THREAD

**Issue by eximiusvir** [bandapps/bandapps.github.io#22]
Just a simple user education issue, you may want to make people aware via an FAQ.

 I have a Withings WiFi scale which sync's my weight, BMI, and body fat percentage to Apple Health. When I installed HBB, I turned on all Categories and in most cases (except weight & BMI) I placed HBB as the top priority in sources. 

Currently MS Health does not appear to have a means of connecting to the WiFi scale and sync'ing weight, so I have found that each morning when I manually sync HBB, my weight measurement is erratic. Logging what I view as my actual weight (from Withings) to my last static entry I entered somewhere in MS Health. 

Essentially I found that either HBB (or more likely MS Health) pulls the latest weight value entered and since that was a static value (215) every entry it logs is 215, followed by my morning measurement. 

With this in mind, unless a HBB user is diligent about manually entering their weight with a consistency, if they have a (primary) means of measurement, it's likely a good idea to disable Weight and BMI Sync'ing for HBB. Setting a lower priority in Sources still logs the manual weight resulting in unreliable visual readings in Apple Health. 

*ALTERNATIVELY* is it possible for HBB to read weight sources and push that weight to MS Health? I'm not sure what the MS Health API allows (can you write to it?) it would be a great way to add even more value to the app. 

Thoughts? (Not sure what's possible)

**Comment by J-L** [comment]
Unfortunately MS does not provision any way to inject data into its data right now- their health api is in ‘beta’ still.

Another user has also requested the ability to turn off weight, so most likely it will make it into a future release

Best regards

John

**Comment by J-L** [comment]
Hey, you can actually tell Apple Health that you want to disable HBB from being able to sync certain bits. In Apple Health, go to Sources> Band health Bridge and toggle the elements you don't want synced!

Best regards

John
