### ISSUE TITLE
Cannot Turn Off Weight and BMI from BandHealthBridge and Stairs too

### ISSUE THREAD

**Issue by mkg3** [bandapps/bandapps.github.io#23]
In Apple Health app, there are selections for BandHealthBridge (BHB) to write date from MS Health.  In those choices, I have turned off weight and BMI, as I use a smart body analyzer that provides these data.

Unfortunately, when syncing, BHB writes fixed data from MS Health, even though its turned off.  Additionally, when looking at sync info in BHB, it shows that weight data was synced.  I believe its a bug.

The other thing is it would be good to pull Stairs data from MS Band to Apple Health.

Thanks for addressing these items in advance.

**Comment by bandapps** [comment]
Hey MKG3,

I will add the ability to turn off syncs in a future release, but in the interim you can (In Apple Health) go Weight > Share Data switch the order of data sources so your smart scale is on top.  That will change where the graph gets its own data.

Thanks for your input!

John
