### ISSUE TITLE
Feature Request: Laboratory

### ISSUE THREAD

**Issue by DavidGoldwasser** [bandapps/bandapps.github.io#24]
Apps look great, just got bundle and Bridge, here few comments on Laboratory.

1. IP support in live view would be great.
2. Distance runs off the screen, so I can't get full number.I can see 3,000,000 meters, and there is a diget after that. I bike 100-200 miles a month. I assume this goes back to original band about 18 months ago vs. just the few months I've had the band 2.
3. Would there be a way to show elevation vs just pressure
4. I can't trigger a reading for UV from this. That would be nice.

This last one is just a question vs. feature request. I notice the Temperature on location is different than skin temp, didn't realize there were two temperature sensors, but that is great.

**Comment by J-L** [comment]
1. IP support?! (not sure what this is)
2. I also got my band in december, but I'm mostly bipedal and live in Canada so I haven't seen this issue- But Ill add it to my change list for the next release,
3. Ill poke around the API and see if I can get elevation from it.
4. UV reads very infrequently- mine always reports 'none' as its not summer yet.  Is yours reporting none or is it '-.-'?

Best regards
John

**Comment by DavidGoldwasser** [comment]
1. Sorry, by IP I mean inch/pound. Basically. So distance in feet or miles, and temperature in fahrenheit.

4. Sorry, looks like it works fine. My UV starts as '-.-' but then does go to none. When I went outside, it went to low (cloudy morning), so looks like it works.

**Comment by J-L** [comment]
in 1.3!

**Comment by DavidGoldwasser** [comment]
Thanks, works great!
