### ISSUE TITLE
iOS 9.3 - BHB crashing on launch

### ISSUE THREAD

**Issue by eximiusvir** [bandapps/bandapps.github.io#26]
I know I sync'd successfully yesterday; however as of this morning BHB is crashing immediately on launch. 

Comfortable to delete and reinstall to identify if that resolves the issue, but want to check if that's going to negatively impact me (any known issues?) prior to attempting.

**Comment by J-L** [comment]
Hey!

You can delete and reinstall it- you can also tell it to delete all underlying data too and reload it.

Ill try to work out what the crash is caused by.  Thanks for reporting it!

John

**Comment by eximiusvir** [comment]
That was weird... Opened the app one more time before uninstalling and it appears to have worked. 

Not sure the type of telemetry you have instrumented / are able to acquire from users apps, but the incident / crash time would have been within 10 minutes of my original post (PST). 

Mike
