### ISSUE TITLE
Sync intraday data as opposed to daily summaries

### ISSUE THREAD

**Issue by brainicus** [bandapps/bandapps.github.io#29]
It appears BHB drives by daily summaries provided by Microsoft Health only, without relying on Band sensors. I'm wondering if you could also create a background process that reads sensors every now and then (particularly, heart rate sensor) and adds this info to Health?

Currently, heart rate available from BHB is reported once per hour, which is in quite stark contrast to Apple Watch that captures it at least every 10 minutes and sometimes more often.

**Comment by J-L** [comment]
Hey Brainicus, such a feature is slightly out of scope for the HBB, but if microsoft ever gives more granular data access to the cloud API, it will certainly be added. 

Thank you for you input
