### ISSUE TITLE
how about a new app?

### ISSUE THREAD

**Issue by mrose17** [bandapps/bandapps.github.io#3]
hi. i would very much like to see the heartbeat and uv stats go from my msftband2 to the health app on my iPhone.

i suspect that with band laborator you are about 90% done in doing that! instead of the third panel ("Post") taking parameters to post data via http/s, simply allow the user to select hb and/or uv, and specify the upload interval.

it could be a separate app or an in app purchase for band laboratory -- whatever is easier for you!

thanks,

/mtr

**Comment by J-L** [comment]
Hey mrrose,

I am actually working on a app that is in the review queue right now called Band Health Bridge that should take your data from the Cloud API and inject it into your Apple Health app.

It uses the Cloud API, rather than the MS Band SDK (which is what band Lab does)  to capture data from your MS Health account. 

Here is a list of data it collects:
-Heart Rate 
-Calories Burned
-Workouts
-Walking/Running Distance
-Cycling Distance
-Steps Taken
-Sleep Analysis
-Weight
-Height
-Body Mass Index

As you can see, it is lacking UV Index.  For whatever reason, the API does not populate this field, and so I will not be able to put that into the health app ( Though I have emailed Microsoft about adding that into their API).

The app should be available within 1 week.

Best regards

John

**Comment by mrose17** [comment]
you are a _genius_ ... many thanks. i'll check back with the app store in a week... many thanks

odd that they didn't include the UV index in the API, but i'm sure they can add the three lines of glue to make it happen (-;

best,

/mtr

**Comment by J-L** [comment]
They haven't updated the Cloud API since July... when the Band 1 was out- I think the Band 1 didn't have this sensor.

Ill post back here when it has been added to the store.  It might be a bit longer as well, it interacts with Apple's Health kit so might get greater scrutiny.
John

**Comment by mrose17** [comment]
understood on both counts.  many thanks!

ps: my next "impossible task" figure out how to get apple health to record lab results (e.g., cholesterol, HbA1c) so i can easily track that. unlike the open dictionary approach taken by msft heathvault, apple health appears to have a closed dictionary (you can add metadata to the pre-defined types -- in this case -- HKQuantitySample -- but can't define new types)... sigh.

while the msft healthvault approach is open-ended, you can import via the standardized (but unavailable to consumer) CCD/CCR formats.

regardless, i think there are great opportunities for indy developers to find the holes and plug them, because, quite frankly, the big players don't seem to be sweating the small stuff. best!

**Comment by J-L** [comment]
Yeah, I saw that (this will be the first HealthKit app) and I was unimpressed by the list of values that you can import into it.  

HealthVault is actually unavailable in my home and native land (Canada) so I can't even have a look at it.   

Though this is just a spare time gig right now, I've been trying to push out an app a week- and to be honest Im running out of ideas- I've covered a lot of the basics.  You ideas would be welcome, either Band or not Band related.  Email me if you would like.

John

**Comment by mrose17** [comment]
i'm very sorry to hear that you can't get healthvault in your neck of the woods (though frankly, unless you actually like repeated frustration, you might consider the geolocation limits to be fortuitious...) at least HK isn't locking you out (-;

i'll shoot you a couple of ideas via email. thanks!

**Comment by mrose17** [comment]
FYI:  2 emails sent!

**Comment by J-L** [comment]
https://itunes.apple.com/us/app/band-health-bridge/id1078869961 

Band Health Bridge - the Apple Health sync app is available on iTunes.

**Comment by mrose17** [comment]
Hmm. It says not available in the US store!

/mtr




On Wed, Feb 3, 2016 at 1:27 PM -0800, "John Justin Lee" <notifications@github.com> wrote:












https://itunes.apple.com/us/app/band-health-bridge/id1078869961 



Band Health Bridge - the Apple Health sync app is available on iTunes.

**Comment by J-L** [comment]
I _just_ released it a minute ago. I think the status is still propagating... :+1:

**Comment by mrose17** [comment]
Yep

/mtr




On Wed, Feb 3, 2016 at 1:32 PM -0800, "John Justin Lee" <notifications@github.com> wrote:












I just released it a minute ago. I think the status is still propagating...

**Comment by mrose17** [comment]
Brilliant!

/mtr




On Wed, Feb 3, 2016 at 1:32 PM -0800, "John Justin Lee" <notifications@github.com> wrote:












I just released it a minute ago. I think the status is still propagating...
