### ISSUE TITLE
BHB doesn't sync sleep

### ISSUE THREAD

**Issue by mickfeech** [bandapps/bandapps.github.io#30]
It appears that the sleep analysis isn't syncing presently

**Comment by J-L** [comment]
Oh yes it does! Do you have other sources of sleep data?  They get a priority, and the one at the top is the highest- even if its not currently injecting any data.  Go to Sleep Analysis > Share Data  and let me know if you have any other sources above BHB.

Kind regards

John

**Comment by mickfeech** [comment]
BHB is the only source. It's inserting data for everything else except sleep analysis.

**Comment by bandapps** [comment]
:cry:  Alright Mick, I'm sorry for the disbelief....Could you provide me with some more information?

iOS version:
Phone type:
Version Band:
Sometime/All the time?:
Could you provide me with a couple screen shots of the MS Health sleep pages that haven't been synced? (perhaps there is a field that is null or so that is causing the app to disregard it...)

Thanks Mick, we'll work through this to get a fix.

John

**Comment by mickfeech** [comment]
IOS 9.3
Iphone 6s
Band 2
All the time. I'll grab some caps and post them in a bit.

**Comment by mickfeech** [comment]
![image](https://cloud.githubusercontent.com/assets/658759/14193870/be06a72a-f776-11e5-9ec0-0c947212b419.png)

**Comment by mickfeech** [comment]
none of those have sync'd

**Comment by bandapps** [comment]
Could you send a photo of a sleep like this?

<img width="906" alt="screen shot 2016-03-31 at 6 13 54 pm" src="https://cloud.githubusercontent.com/assets/16301105/14195296/79e29d7e-f76c-11e5-8184-0934dcc31130.png">

**Comment by mickfeech** [comment]
![image](https://cloud.githubusercontent.com/assets/658759/14195319/0571d792-f786-11e5-82c9-b9b4a4de5512.png)

**Comment by J-L** [comment]
I am kind of at a loss.  Could I ask you to delete the app and redownload it?  you can delete the data from apple health when it asks you- When you redownload you’ll get it back again.

**Comment by mickfeech** [comment]
Did that, no change.

**Comment by J-L** [comment]
Hey Mick, Im busy this weekend, but can I organize a couple minutes of your time after 5pm PST?  I'd like you to team viewer into my computer where I can see the output of the console when it is loading data.

Best regards

John

**Comment by mickfeech** [comment]
Everything started to sync this morning.
