### ISSUE TITLE
Workout labeled as "Play" Band Health Bridge

### ISSUE THREAD

**Issue by sdr0713** [bandapps/bandapps.github.io#31]
All of my data points for workouts carry the label "Play" as the workout type.  It doesn't feel like "play" - LOL.  Seriously though, since Microsoft Band has labels for those activities, could they be applied instead of the generic one of "play"?

Thanks in advance

**Comment by bandapps** [comment]
Hey there! I've notice that Microsoft has started populating the activityType field correctly, so I think I can do that.  Microsoft's own terminology considers everything other than run and biking to be 'freeplay', so i placed everything under there. Ill add this to my todo for 1.3

**Comment by sdr0713** [comment]
That would be cool.  Thanks!  And BTW - this app is pretty sweet and well worth the cost.

**Comment by J-L** [comment]
Fixed in 1.3.... in review queue soon.
