### ISSUE TITLE
tiles not adding to the band 

### ISSUE THREAD

**Issue by ayanez17** [bandapps/bandapps.github.io#32]
I bought the bundle of all apps and the ones that should add a tile to my Microsoft band are not doing so. I've tried the bandsnap, bandtimer,and bandlist. When it asked about adding them to the band I press yes, and my band 2 says it is updating and then once it's done the tile is not added to the Microsoft band.

**Comment by J-L** [comment]
Hey,
Could you restart your band and phone?  It seems this might be a glitch on the Microsoft side...Also the icons should appear in the far right of the app strip on the band- hopefully a restart will fix this.

**Comment by ayanez17** [comment]
I have restarted the apps, the band, and my phone and that didn't help. I have also tried to look everywhere for the icons and nothing appears.

**Comment by J-L** [comment]
Is this with the latest fw on the band? Previous versions had a limit of 12 tiles, so you could run out.
Gear Icon> i > second page 
mine reports 2.04442.0 26R

**Comment by J-L** [comment]
Could you also try deleting the apps and redownloading them?  I don't think this will do anything, but it is worth a shot

**Comment by J-L** [comment]
Also, could you try removing one of Microsoft's own tiles and re-adding it?  If that does not work ... possible hardware defect.

**Comment by ayanez17** [comment]
The firmware I have is 2.04441.0 26R. I know that is different than yours, I updated it yesterday and I don't have the ability to update it again. I have found a temporary fix to the solution. what I did was to delete tiles so that I have less than 12. I then add the bandapps, I then re-add the apps I took off using the Microsoft health app. This works. I still have the ability to add 20 tiles but for some reason I need to add the bandapps before I reach the 12 tile limit.

**Comment by J-L** [comment]
hmm. Might be a MS bug where you can add 3rd party apps up till 12, but then 8 slots are reserved for 1st party apps. Ill investigate when I get off work and bug someone at Microsoft if this is the case.

**Comment by J-L** [comment]
Actually, I have a feeling what it is.  The apps are built with the MS Band SDK- that SDK probably has a hard limit of 12 to what it can insert.

**Comment by ayanez17** [comment]
I think that might be the case. Also, I'm a student at MIT and I want to create some MS Band I was wondering if you could point me in the right direction.

**Comment by J-L** [comment]
https://developer.microsoftband.com/bandSDK

Its actually pretty straight forward if you know iOS already... if not it will take a little while to spin up that skill set.

**Comment by gmaddry** [comment]
I also had a problem adding the tile. I remove some MS tiles as was able to add List. Elsewhere I have seem this problem described as 3rd party apps not using the latest SDK.

**Comment by demartinofra** [comment]
Same problem here. I bought the bundle for iPhone but I'm not able to use the apps that require a tile with more than 12 tiles. If I add the microsoft tiles after having installed the app's tiles, those are removed automatically. Could you please try to update the SDK or figure out a solution to this issue otherwise I won't be able to use those apps?

**Comment by bandapps** [comment]
Hey all,
Microsoft just released the sdk for 3rd parties about 4 days ago. The recent update to time tracker and list now include these changes!

Band snap will be coming soon, but in the mean time you can remove  other tiles until you have 11, then add band snap.

Sorry about the wait... I was also waiting on ms for the third party sdk

**Comment by demartinofra** [comment]
They are working correctly right now :) Thanks for the quick fix!
