### ISSUE TITLE
I am in China, BHB can not be synchronized with apple health?

### ISSUE THREAD

**Issue by wexefe** [bandapps/bandapps.github.io#34]
Synchronized MB web page data is successful, but apple health can not be synchronized with the BHB, is my problem?

**Comment by J-L** [comment]
Hey Wex,
I don't see why not... Could you redownload the app and run it- when complete, what does info say (Top right corner)

Do you have other data sources in apple health?  Is all data missing or just part?

**Comment by wexefe** [comment]
Thank you for your reply, before the UP24 data, maybe the problem of China's network, I repeat the installation of this APP N times, and now has been successfully synchronized.
