### ISSUE TITLE
Doesn't synchronize sleep data on Apple health

### ISSUE THREAD

**Issue by indameza** [bandapps/bandapps.github.io#35]
Please let me know if you will fix and when. I bought the app for that purpose.

**Comment by J-L** [comment]
Hey there, do you have other sources of apple health sleep data?

**Comment by indameza** [comment]
Withings - let me delete that app

**Comment by J-L** [comment]
Delete BHB too and reinstall it just to be sure. I think Apple Health with fill this time.

**Comment by indameza** [comment]
Thanks, deleting the other app and reinstalling BHB fixed it. Appreciate the quick response!
