### ISSUE TITLE
Band and Apple Watch

### ISSUE THREAD

**Issue by mwrowbottom** [bandapps/bandapps.github.io#36]
Hi, I'm trialling a band 2 alongside my Apple Watch and would love to have all the data on one place in the apple health app.  Your bridge application seems ideal but I just had a couple of questions before I purchase it.

1. Is the sync smart?  I'm wearing both the Apple Watch and band 2 at the moment, they are both tracking steps for example so don't want to double up when syncing.

2.  Can you do selective sync to avoid doubling up with the Apple Watch,  for example, could I just sync the sleep analysis from the band and nothing else as this is a function not available for the watch.

**Comment by J-L** [comment]
Hey there,
Sorry for the delay in getting back to you. 

Apple health can take in several sources of data, but presents only one.  The way this is sorted out is there is a data sources page which you can reorder the priority.

When the app loads up for the first time it will ask you what permissions you would like. if you want BHB not to sync particular data, you simply leave it disabled

Best regards

John

**Comment by mwrowbottom** [comment]
Perfect, exactly what I need.  Thanks for the quick response, purchasing now!
