### ISSUE TITLE
Set theme colour button

### ISSUE THREAD

**Issue by Sinnerswake** [bandapps/bandapps.github.io#38]
Set theme colour button doesn't seem to work since the last update. Tried uninstalling/reinstalling with no luck. Also would be great to see an option similar to Windows pimp my band app that sets theme colour based on predominant colour in picture. Many thanks.

**Comment by J-L** [comment]
Hey Sinners, Il fix that in a upcoming release- I was doing a relayout and i goofed. and thats a good idea- though I'm not sure how to implement it right now (Maybe some sort of color histogram or something?

Best regards

John

**Comment by Sinnerswake** [comment]
That's great. Possibly a colour histogram is the way to go. Look forward to the update. 

Graeme

**Comment by J-L** [comment]
Fixed in 1.4
