### ISSUE TITLE
Can not set a saver URL

### ISSUE THREAD

**Issue by shintaku55** [bandapps/bandapps.github.io#39]
Hi,

I am useing Band Lab. iOS version is 9.3.2.
Now I can not set a URL for json data send. Is that a issue ? I want to see a screen shot which how to set a URL.

Best,
Hiro

**Comment by bandapps** [comment]
Hey, you have to specify protocol, either http or https

try:
http://127.0.0.1/endpoint <http://127.0.0.1/endpoint>
