### ISSUE TITLE
suggestions: summary history

### ISSUE THREAD

**Issue by mrose17** [bandapps/bandapps.github.io#4]
in addition to band health bridge, i really like sync solver (fitbit to health). 

one of the things that app does is provide a summary screen of what it did (see attached images ... tap "Details" and you get the second screen). i think this is a great feature to add... just a thought!

![img_0212](https://cloud.githubusercontent.com/assets/400552/12832504/43b3f750-cb4f-11e5-8015-5dd5b477bbdd.jpg)
![img_0213](https://cloud.githubusercontent.com/assets/400552/12832508/471edd10-cb4f-11e5-897c-93731e0ab322.jpg)

**Comment by J-L** [comment]
Agreed!  Next time I touch the code I'll add something similar.

Thanks!

**Comment by J-L** [comment]
in 1.1.
