### ISSUE TITLE
Sync was successful, but only latest weight was transferred

### ISSUE THREAD

**Issue by purEnergy** [bandapps/bandapps.github.io#46]
I have about a year and a half of data collected from my Band 2 and logged my weight nearly every day. When I transferred the data using this tool, I only see the current day's weight logged. I do have the Garmin app installed, but it's not connected to HealthKit yet. This is the only app that HealthKit is currently allowing to connect to it. It looks like my activities, heart rate, and sleep got transferred ok.

**Comment by J-L** [comment]
Hey, Microsoft Health api only allows me to grab the current weight from the app.

I can't do any better :|


Best regards

John

**Comment by purEnergy** [comment]
That's a bummer. Fortunately, there's not so many of them that I can't just go and re-enter them manually. It's the least of my worries. Entering some of the other data would be impossible. Thanks. The tool worked great for my migration from the Band 2 to my Garmin Vivoactive HR.


--Marc


________________________________
