### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by AGPVEN** [bandapps/bandapps.github.io#7]
The initial sync seemed to go OK. But after that subsequent syncs we're company by some sort of token error. The error goes by really fast and is hard to read.

**Comment by bandapps** [comment]
Hey AGPVEN,
I think I've isolated the problem, it got through my beta test. I'll be putting a version into the review queue soon

John

**Comment by AGPVEN** [comment]
Great...thx

**Comment by J-L** [comment]
Should be fixed in 1.1. apologies!
