### ISSUE TITLE
Feature request: throttling post speed

### ISSUE THREAD

**Issue by chriskacerguis** [bandapps/bandapps.github.io#9]
Hi!  This is a great app!  Any chance of setting up a setting to add throttling for the post?  I'd like to be able to use it over a cell connection.

**Comment by bandapps** [comment]
There are 2 ways I can do throttling. Send only 1/x value or send all values 1/x times

Which is more useful?

**Comment by chriskacerguis** [comment]
I would say send all values at X interval (e.g. 5 minutes send a JSON payload with all data at that moment).  I would guess that the JSON payload is not large, it's just the frequency that kills you.

**Comment by J-L** [comment]
send me your email!

**Comment by J-L** [comment]
in 1.3!
